// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJtRhkLTDwLKOugsv4QbdE5IZ9xBXQG0M',
    appId: '1:535938272152:web:2aa96a587f7e8e80e7b9ed',
    messagingSenderId: '535938272152',
    projectId: 'my-first-data-base-1b0ad',
    authDomain: 'my-first-data-base-1b0ad.firebaseapp.com',
    databaseURL: 'https://my-first-data-base-1b0ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-first-data-base-1b0ad.firebasestorage.app',
    measurementId: 'G-E76SLLJFHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzFCm1HNN199cT_sToL6-RAi3CgT3uwpM',
    appId: '1:535938272152:android:0ceea959763d10e9e7b9ed',
    messagingSenderId: '535938272152',
    projectId: 'my-first-data-base-1b0ad',
    databaseURL: 'https://my-first-data-base-1b0ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-first-data-base-1b0ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnFjS1QqlWq4_3wVR4mbriq2IudQ5o1oU',
    appId: '1:535938272152:ios:a74cae2d1656dbe6e7b9ed',
    messagingSenderId: '535938272152',
    projectId: 'my-first-data-base-1b0ad',
    databaseURL: 'https://my-first-data-base-1b0ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-first-data-base-1b0ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnFjS1QqlWq4_3wVR4mbriq2IudQ5o1oU',
    appId: '1:535938272152:ios:a74cae2d1656dbe6e7b9ed',
    messagingSenderId: '535938272152',
    projectId: 'my-first-data-base-1b0ad',
    databaseURL: 'https://my-first-data-base-1b0ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-first-data-base-1b0ad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJtRhkLTDwLKOugsv4QbdE5IZ9xBXQG0M',
    appId: '1:535938272152:web:f3ceb6e3f09f81d9e7b9ed',
    messagingSenderId: '535938272152',
    projectId: 'my-first-data-base-1b0ad',
    authDomain: 'my-first-data-base-1b0ad.firebaseapp.com',
    databaseURL: 'https://my-first-data-base-1b0ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-first-data-base-1b0ad.firebasestorage.app',
    measurementId: 'G-M2Q8Z0DBSG',
  );

}