// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4pcBjHHo24ExW7kf0P1dlplI26NnhpoA',
    appId: '1:1034636586264:android:1dd4de77d7da4f4c60826d',
    messagingSenderId: '1034636586264',
    projectId: 'fooddetection-69088',
    databaseURL: 'https://fooddetection-69088-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddetection-69088.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuL2J4vJo5vPpIjJoXRusgZfdCAO8DcG4',
    appId: '1:1034636586264:ios:d4eebabf574a3eca60826d',
    messagingSenderId: '1034636586264',
    projectId: 'fooddetection-69088',
    databaseURL: 'https://fooddetection-69088-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddetection-69088.firebasestorage.app',
    iosClientId: '1034636586264-1o6t3sd1n7d6uselpu9g84iljgs9qh1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
